version: '3'

services:
  my_golang_service:
    build: .  # Dockerfile 的目录
    ports:
      - "8080:8080"

  mysql_db:
    image: mysql:8.0
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zhouyi
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d  # 数据初始化